### ISSUE TITLE
backup magazines gives you multiple uses of the second beacon

### ISSUE THREAD

**Issue by nutshel-u** [Phys09/ROR2-Captain-Beacon-Cooldown#1]
just what the title says, for some weird reason backup magazine considers the m2 beacon as a secondary skill so it gives it multiple uses with no cooldown and im not sure about this but i think waiting for just one m2 beacon to recharge will give you the full charges that you would have with backup mags without waiting the cooldown.
no idea how to fix it tbh i just was messing with mods i have no idea of coding.
also great work btw the cooldown tweaks may be small but it really makes captain a ton more enjoyable and flexible so keep up the great work man 👍👍👍

**Comment by Phys09** [comment]
Fixed in the latest version (as of writing)
